dist: xenial
sudo: required
language: c

branches:
  only:
  - v8.8
  - v8.9
  - v8.10
  - v8.11

cache:
  apt: true
  directories:
  - $HOME/.opam

addons:
  apt:
    packages:
    - gcc-multilib

env:
  global:
  - OPAMJOBS="2"
  - OPAMROOTISOK="true"
  - OPAMYES="true"
  - NJOBS="2"
  - COQ_REPOS="https://github.com/coq/coq.git"
  - COQ_VERSION="v8.11"
  - COQ_BRANCH="v8.11"
  - COQ_CONF="-local -native-compiler no -coqide no"
  - COMPILER="4.07.1"
  - SERAPI_COQ_HOME="$HOME/coq-$COQ_VERSION/_build/install/default/lib/"
  # Main test suites
  matrix:
  # - TEST_TARGET="build"   COMPILER="4.07.1"       EXTRA_OPAM="coq"
  # - TEST_TARGET="test"    COMPILER="4.07.1"       EXTRA_OPAM="coq coq-mathcomp-ssreflect"
  # - TEST_TARGET="js-dune" COMPILER="4.07.1+32bit" EXTRA_OPAM="coq js_of_ocaml js_of_ocaml-lwt"
  # Don't test opam in 8.11 [yet]
  - TEST_TARGET="test"
  - TEST_TARGET="js-dune" COMPILER="4.07.1+32bit" EXTRA_OPAM="js_of_ocaml js_of_ocaml-lwt"

install:
- sudo curl -sL https://github.com/ocaml/opam/releases/download/2.0.5/opam-2.0.5-x86_64-linux -o /usr/bin/opam
- sudo chmod 755 /usr/bin/opam
- opam init -c "$COMPILER" --disable-sandboxing
- opam switch set "$COMPILER"
- eval $(opam env)
# OPAM 2 seems quite broken here
- opam repos add coq-released http://coq.inria.fr/opam/released
- opam config set-global jobs $NJOBS
- opam pin add -y -n --kind=path coq-serapi .
- opam install -y --deps-only -j $NJOBS coq-serapi
- opam pin remove coq-serapi
- opam list
- >
  if [[ -v SERAPI_COQ_HOME ]]; then
    git clone --depth=3 -b "$COQ_BRANCH" "$COQ_REPOS" "$HOME/coq-$COQ_VERSION" &&
    pushd "$HOME/coq-$COQ_VERSION"        &&
    make -f Makefile.dune coq             &&
    popd;
    PATH="$HOME/coq-$COQ_VERSION/_build/install/default/bin":$PATH &&
    git clone --depth=3 -b master https://github.com/math-comp/math-comp.git &&
    pushd math-comp/mathcomp/ssreflect &&
    make && make install &&
    popd;
  fi
- if [[ -v EXTRA_OPAM ]]; then opam install --ignore-constraints-on=coq $EXTRA_OPAM; fi

script:
- set -e
- echo 'Building SerAPI...' && echo -en 'travis_fold:start:serapi.build\\r'
- make -j "$NJOBS" SERAPI_COQ_HOME="$SERAPI_COQ_HOME" "$TEST_TARGET"
- ls -lR _build/install/default/ || true
- ls -lR _build/default/sertop/*.js || true
- echo -en 'travis_fold:end:serapi.build\\r'
