dist: trusty
sudo: required
language: ocaml
cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
env:
  global:
  - NJOBS=2
  - COQ_VERSION="v8.7"
  - COQ_REPOS=https://github.com/coq/coq.git
  # - COQ_REPOS="git://scm.gforge.inria.fr/coq/coq.git"
  - COQ_BRANCH="v8.7"
  # system is == 4.02.3
  - COMPILER="4.06.0"
  - BASE_OPAM="camlp5 cmdliner ppx_deriving ppx_import ppx_sexp_conv sexplib js_of_ocaml js_of_ocaml-lwt ppx_deriving_yojson"
  # Main test suites
  # matrix:
  # - TEST_TARGET="test1"
  # - TEST_TARGET="test2"

install:
- "[ -e .opam ] || opam init -j ${NJOBS} --compiler=${COMPILER} -n -y"
- eval $(opam config env)
- opam config var root
- opam update
- opam install -j ${NJOBS} -y ${BASE_OPAM} ${EXTRA_OPAM} # yojson ppx_deriving_yojson
- opam list
- git clone --depth=3 -b ${COQ_BRANCH} ${COQ_REPOS} ${HOME}/coq-${COQ_VERSION}
- pushd ${HOME}/coq-${COQ_VERSION}
- ./configure -local -native-compiler no -coqide no
- make -j ${NJOBS}
- make -j ${NJBOS} byte
- popd

script:
- echo 'Building SerAPI...' && echo -en 'travis_fold:start:serapi.build\\r'
- make -j ${NJOBS} SERAPI_COQ_HOME="${HOME}/coq-${COQ_VERSION}/" serlib
- ls -l _build/serlib/serlib.cmxa
- make -j ${NJOBS} SERAPI_COQ_HOME="${HOME}/coq-${COQ_VERSION}/"
- ls -l _build/sertop/sertop.native _build/sertop/sercomp.native
# XXX Move to a matrix build specific for js
- make -j ${NJOBS} SERAPI_COQ_HOME="${HOME}/coq-${COQ_VERSION}/" sertop_js.byte
- ls -l _build/sertop/sertop_js.byte
- echo -en 'travis_fold:end:serapi.build\\r'
